version: "3"
services:
  postgres-10: &postgres
    image: docker.io/library/postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
    healthcheck:
      timeout: 10s
      interval: 1s
      test: [CMD, pg_isready, -U, postgres, -h, localhost]
      retries: 10
    ports: [5432:5432]
  postgres-11:
    <<: *postgres
    image: docker.io/library/postgres:11-alpine
    ports: [5433:5432]
  postgres-12:
    <<: *postgres
    image: docker.io/library/postgres:12-alpine
    ports: [5434:5432]
  postgres-13:
    <<: *postgres
    image: docker.io/library/postgres:13-alpine
    ports: [5435:5432]
  postgres-14:
    <<: *postgres
    image: docker.io/library/postgres:14-alpine
    ports: [5436:5432]
  mysql-5.7: &mysql
    image: docker.io/library/mysql:5.7
    ports: [3306:3306]
    environment: [MYSQL_ROOT_PASSWORD=password]
    healthcheck:
      test: mysql -u root -p ${MYSQL_ROOT_PASSWORD} --silent --execute 'select 1;'
      interval: 1s
      timeout: 10s
      retries: 60
  mysql-8.0:
    <<: *mysql
    image: docker.io/library/mysql:8.0
    ports: [3307:3306]
  mariadb-10.2:
    <<: *mysql
    image: docker.io/library/mariadb:10.2
    ports: [3308:3306]
  mariadb-10.3:
    <<: *mysql
    image: docker.io/library/mariadb:10.3
    ports: [3309:3306]
  mariadb-10.4:
    <<: *mysql
    image: docker.io/library/mariadb:10.4
    ports: [3310:3306]
  mariadb-10.5:
    <<: *mysql
    image: docker.io/library/mariadb:10.5
    ports: [3311:3306]
  mariadb-10.6:
    <<: *mysql
    image: docker.io/library/mariadb:10.6
    ports: [3312:3306]
  mariadb-10.7:
    <<: *mysql
    image: docker.io/library/mariadb:10.7
    ports: [3313:3306]
  # see https://hub.docker.com/r/cockroachdb/cockroach/tags
  cockroachdb-19.2: &cockroach
    image: docker.io/cockroachdb/cockroach:latest-v19.2
    command: [start-single-node, --insecure] # no password neccessary?
    ports: [26257:26257]
  cockroachdb-20.1:
    <<: *cockroach
    image: docker.io/cockroachdb/cockroach:latest-v20.1
    ports: [26258:26257]

  cockroachdb-20.2:
    <<: *cockroach
    image: docker.io/cockroachdb/cockroach:latest-v20.2
    ports: [26259:26257]

  cockroachdb-21.1:
    <<: *cockroach
    image: docker.io/cockroachdb/cockroach:latest-v21.1
    ports: [26260:26257]

  cockroachdb-21.2:
    <<: *cockroach
    image: docker.io/cockroachdb/cockroach:latest-v21.2
    ports: [26261:26257]

  # TODO: mariadb
  # TODO: db2
  # TODO:
